# Generated by Django 5.0.6 on 2024-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='display_profile',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='display_profile',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
